name: PR Check

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download Artifacts
        uses: ./.github/actions/download-artifacts

      - name: Run tests
        run: pnpm test
        shell: bash

  typecheck:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download Artifacts
        uses: ./.github/actions/download-artifacts

      - name: Build packages
        run: pnpm build
        shell: bash

      - name: Run type check
        run: pnpm -r typecheck
        shell: bash

  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download Artifacts
        uses: ./.github/actions/download-artifacts
        with:
          download-build: 'false'

      - name: Security audit
        run: pnpm audit --audit-level moderate
        shell: bash
