name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download Artifacts
        uses: ./.github/actions/download-artifacts

      - name: Run tests
        run: pnpm test
        shell: bash

      - name: Run test coverage
        run: pnpm -r test:coverage
        shell: bash

  typecheck:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download Artifacts
        uses: ./.github/actions/download-artifacts

      - name: Run type check
        run: pnpm -r typecheck
        shell: bash

  version:
    needs: [test, typecheck]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download Artifacts
        uses: ./.github/actions/download-artifacts

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: [test, typecheck, version]
    runs-on: ubuntu-latest
    if: steps.changesets.outputs.published == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changesets.outputs.tag }}
          release_name: Release ${{ steps.changesets.outputs.tag }}
          body: ${{ steps.changesets.outputs.publishedPackages }}
          draft: false
          prerelease: false
